version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL:-http://localhost:3001}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    environment:
      - PORT=3001
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173} 
